[workspace]
members = [
  "mint_lib",
  "hook",
  "hook_resolvers",
  "workspace_hack",
]

[workspace.package]
repository = "https://github.com/Fedottt-Bo/mint-no-tag"
authors = ["trumank", "jieyouxu", "Fedottt-Bo"]
license = "MIT OR Apache-2.0"
version = "1.2.1"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0.102", features = ["backtrace"] }
fs-err = "3.3.0"
itertools = "0.14.0"
patternsleuth = { git = "https://github.com/trumank/patternsleuth", rev = "5786164" }
postcard = { version = "1.1.3", default-features = false, features = ["alloc"] }
repak = { git = "https://github.com/trumank/repak", rev = "355b5f6" }
reqwest = { version = "0.11.27", default-features = false, features = ["blocking", "rustls", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.149"
snafu = "0.8.9"
steamlocate = "2.1.0"
tokio = "1.51.1"
tracing = { version = "0.1.44", features = ["attributes"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter", "std", "registry"] }

[package]
name = "mint"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "mint_no-tag"
path = "src/main.rs"

[features]
default = ["hook"]
hook = ["dep:hook"]

[dependencies]
ansi_term = "0.12.1"
anyhow.workspace = true
async-trait = "0.1.89"
clap = { version = "4.6.0", features = ["derive"] }
dialoguer = "0.11.0"
directories = "6.0.0"
eframe = "0.31.1"
egui = "0.31.1"
egui_commonmark = "0.20.0"
egui_dnd = "0.12.0"
fs-err.workspace = true
futures = "0.3.32"
hex = "0.4.3"
image = { version = "0.25.10", default-features = false, features = ["png"] }
include_dir = "0.7.4"
indexmap = { version = "2.13.1", features = ["serde"] }
inventory = "0.3.24"
itertools.workspace = true
mint_lib = { path = "mint_lib" }
modio = { git = "https://github.com/trumank/modio-rs.git", rev = "d979c0a", default-features = false, features = ["rustls-tls"] }
obake = { version = "1.0.5", features = ["serde"] }
opener = "0.7.2"
path-slash = "0.2.1"
postcard.workspace = true
rayon = "1.11.0"
regex = "1.12.3"
repak.workspace = true
reqwest-middleware = "0.2.5"
reqwest.workspace = true
rfd = "0.15.4"
rust-ini = "0.21.3"
self_update = { version = "0.42.0", default-features = false, features = ["archive-zip", "rustls"] }
semver = "1.0.28"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
snafu.workspace = true
steamlocate.workspace = true
strum = { version = "0.27.2", features = ["derive"] }
task-local-extensions = "0.1.4"
tempfile = "3.27.0"
thiserror = "2.0.18"
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
typetag = "0.2.21"
uasset_utils = { git = "https://github.com/trumank/uasset_utils" }
unreal_asset = { git = "https://github.com/trumank/unrealmodding", branch = "patches" }
url = "2.5.8"
workspace_hack = { path = "workspace_hack" }
zip = { version = "8.5.1", default-features = false, features = [
  "aes-crypto", "time",
  "deflate", "deflate64", "deflate-flate2", "deflate-zopfli",
  "bzip2", "zstd", "lzma", "xz", "ppmd"
] }

[target.'cfg(target_env = "msvc")'.dependencies]
hook = { path = "hook", artifact = "cdylib", optional = true, target = "x86_64-pc-windows-msvc"}
[target.'cfg(not(target_env = "msvc"))'.dependencies]
hook = { path = "hook", artifact = "cdylib", optional = true, target = "x86_64-pc-windows-gnu"}

[profile.dist]
inherits = "release"
codegen-units = 1
lto = true
strip = true

[profile.dev]
opt-level = 3
lto = "off"

[dev-dependencies]
mockall = "0.13.1"
