[package]
name = "hook"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
bitflags = "2.9.3"
fs-err.workspace = true
hook_resolvers = { path = "../hook_resolvers" }
mint_lib = { path = "../mint_lib" }
patternsleuth = { workspace = true, features = ["process-internal", "image-pe"] }
postcard.workspace = true
proxy_dll = { git = "https://github.com/trumank/proxy_dll.git" }
repak.workspace = true
retour = { git = "https://github.com/Hpmason/retour-rs", features = ["static-detour"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-appender = "0.2.3"
tracing.workspace = true
widestring = "1.2.0"
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_System_SystemServices",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_Threading",
] }
